name: esafetyadviser
favicon: null
layout_spectrum: 0.88449
typography_spectrum: 0.24945501517504454
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2a4695'
    - '#2275b8'
    - '#000000'
    - '#0000ff'
    - '#30a8dd'
  brandStrength: 0.8514086168725044
  lightness: 0.7142190511804074
  saturation: 0.5872951694764197
  rhythmicContrast: 0.8598199845291674
purpose: []
